version: "3.8"
services:
  postgres:
    container_name: "reddit-newsletter-postgres"
    networks:
      - reddit-newsletter
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: reddit-newsletter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    command: postgres -c 'max_connections=500'
    volumes:
      - ./pg-data:/var/lib/postgresql/data
volumes:
  pg-data:

networks:
  reddit-newsletter:
