apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: subreddit-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: subreddit-worker
              image: reddit-newsletter/worker
              imagePullPolicy: Never
          restartPolicy: Never
