apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: publish-cronjob
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: publish-worker
              image: reddit-newsletter/publish-worker
              imagePullPolicy: Never
          restartPolicy: Never
